ARTICLE  = slides
all:
	pdflatex slides
	#bibtex slides
	#biber slides
	pdflatex slides
	#pdflatex slides

clean:
	rm -R *~; rm *.bbl *.blg slides.pdf *.ps *.dvi *.aux *.out; rm *.idx; rm *.log; rm *.toc; rm */*~; rm *.xml; rm *.vrb; rm *.snm; rm *.nav; rm *.bcf

